### PR TITLE
Keep status bar hidden after app switch

### PR DESCRIPTION
**Pull request by ArnoldasM**
Keeps top status bar hidden after app switching
Full screen with cutouts
Replaced some deprecated code
### Issue:
Screenshot_20220725_142034_com lagradost quicknovel debug

### After Fix:
Screenshot_20220725_151321_com lagradost quicknovel debug

### CODE REVIEW

**Comment by ArnoldasM** [comment]
> 🤔 intresting

What's so interesting? 😅

**Comment by LagradOst** [comment]
I currently use deprecated hide in [cs3](https://github.com/LagradOst/CloudStream-3), could I use this in it too (sometime in the future)?

**Comment by LagradOst** [comment]
btw ready to merge? 👍

**Comment by ArnoldasM** [comment]
> I currently use deprecated hide in [cs3](https://github.com/LagradOst/CloudStream-3), could I use this in it too (sometime in the future)?

Check if you want to keep these lines:
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P){
            window.attributes.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
        }`

If removed screen cutout will not be seen. If kept, cutout will be seen

**Comment by ArnoldasM** [comment]
> 🤔 intresting

You can see issue here:
[https://drive.google.com/file/d/1Kuyh5qcUI3M_6piYt5j0iRhzclkweak-/view?usp=drivesdk]()

**Comment by LagradOst** [comment]
ait, but do you want this merged or do you need to change anything?

**Comment by ArnoldasM** [comment]
> ait, but do you want this merged or do you need to change anything?

Ok, I removed the cutout support. Used a little bit with cutout and found it a little bit irritating. Now its ready to merge.

**Pull request merged**
