### PR TITLE
add new arabic source

### PR DESCRIPTION
**Pull request by ahmedgamal17**
add [KolNovel](https://kolnovel.com)

### CODE REVIEW

**Comment by Blatzar** [comment]
See https://github.com/ahmedgamal17/QuickNovel/pull/1 for preventing beginning after the end causing crashes.
The parsed somehow fucks up for that title: 
image

**Comment by LagradOst** [comment]
Wait, you added another provider?

**Comment by ahmedgamal17** [comment]
Yes it was using the same theme so I just modified little things but still the bug with (the beginning after the end) novel 🥲

**Comment by LagradOst** [comment]
Do you want to merge?

**Comment by ahmedgamal17** [comment]
Ok you merge it

**Pull request merged**
